import '@/globals.css'

import { type Metadata } from 'next'
import { Geist } from 'next/font/google'

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create-mono',
}

const geist = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
})

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${geist.variable}`}>
            <body className="antialiased">{children}</body>
        </html>
    )
}
