import '@/globals.css'

import { type Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create-mono',
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className="antialiased">{children}</body>
        </html>
    )
}
