services:
  db:
    image: postgres:17-alpine
    container_name: test-postgresql
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test

volumes:
  data:
